/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppTrendingRouteImport } from './routes/_app.trending'
import { Route as AppSimulcastRouteImport } from './routes/_app.simulcast'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLatestEpisodesRouteImport } from './routes/_app.latest-episodes'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppForYouRouteImport } from './routes/_app.for-you'
import { Route as AppContinueWatchingRouteImport } from './routes/_app.continue-watching'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppCommunityAnimeIdRouteImport } from './routes/_app.community.$animeId'
import { Route as AppAnimeIdRouteImport } from './routes/_app.anime.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendingRoute = AppTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulcastRoute = AppSimulcastRouteImport.update({
  id: '/simulcast',
  path: '/simulcast',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLatestEpisodesRoute = AppLatestEpisodesRouteImport.update({
  id: '/latest-episodes',
  path: '/latest-episodes',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppForYouRoute = AppForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => AppRoute,
} as any)
const AppContinueWatchingRoute = AppContinueWatchingRouteImport.update({
  id: '/continue-watching',
  path: '/continue-watching',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityAnimeIdRoute = AppCommunityAnimeIdRouteImport.update({
  id: '/$animeId',
  path: '/$animeId',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppAnimeIdRoute = AppAnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assistant': typeof AppAssistantRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/continue-watching': typeof AppContinueWatchingRoute
  '/for-you': typeof AppForYouRoute
  '/home': typeof AppHomeRoute
  '/latest-episodes': typeof AppLatestEpisodesRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/simulcast': typeof AppSimulcastRoute
  '/trending': typeof AppTrendingRoute
  '/watchlist': typeof AppWatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/anime/$id': typeof AppAnimeIdRoute
  '/community/$animeId': typeof AppCommunityAnimeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assistant': typeof AppAssistantRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/continue-watching': typeof AppContinueWatchingRoute
  '/for-you': typeof AppForYouRoute
  '/home': typeof AppHomeRoute
  '/latest-episodes': typeof AppLatestEpisodesRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/simulcast': typeof AppSimulcastRoute
  '/trending': typeof AppTrendingRoute
  '/watchlist': typeof AppWatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/anime/$id': typeof AppAnimeIdRoute
  '/community/$animeId': typeof AppCommunityAnimeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/community': typeof AppCommunityRouteWithChildren
  '/_app/continue-watching': typeof AppContinueWatchingRoute
  '/_app/for-you': typeof AppForYouRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/latest-episodes': typeof AppLatestEpisodesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/simulcast': typeof AppSimulcastRoute
  '/_app/trending': typeof AppTrendingRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/anime/$id': typeof AppAnimeIdRoute
  '/_app/community/$animeId': typeof AppCommunityAnimeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assistant'
    | '/community'
    | '/continue-watching'
    | '/for-you'
    | '/home'
    | '/latest-episodes'
    | '/profile'
    | '/search'
    | '/simulcast'
    | '/trending'
    | '/watchlist'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
    | '/anime/$id'
    | '/community/$animeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assistant'
    | '/community'
    | '/continue-watching'
    | '/for-you'
    | '/home'
    | '/latest-episodes'
    | '/profile'
    | '/search'
    | '/simulcast'
    | '/trending'
    | '/watchlist'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
    | '/anime/$id'
    | '/community/$animeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/assistant'
    | '/_app/community'
    | '/_app/continue-watching'
    | '/_app/for-you'
    | '/_app/home'
    | '/_app/latest-episodes'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/simulcast'
    | '/_app/trending'
    | '/_app/watchlist'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/anime/$id'
    | '/_app/community/$animeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trending': {
      id: '/_app/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AppTrendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulcast': {
      id: '/_app/simulcast'
      path: '/simulcast'
      fullPath: '/simulcast'
      preLoaderRoute: typeof AppSimulcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/latest-episodes': {
      id: '/_app/latest-episodes'
      path: '/latest-episodes'
      fullPath: '/latest-episodes'
      preLoaderRoute: typeof AppLatestEpisodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/for-you': {
      id: '/_app/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof AppForYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/continue-watching': {
      id: '/_app/continue-watching'
      path: '/continue-watching'
      fullPath: '/continue-watching'
      preLoaderRoute: typeof AppContinueWatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/community/$animeId': {
      id: '/_app/community/$animeId'
      path: '/$animeId'
      fullPath: '/community/$animeId'
      preLoaderRoute: typeof AppCommunityAnimeIdRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/_app/anime/$id': {
      id: '/_app/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AppAnimeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCommunityRouteChildren {
  AppCommunityAnimeIdRoute: typeof AppCommunityAnimeIdRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunityAnimeIdRoute: AppCommunityAnimeIdRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppContinueWatchingRoute: typeof AppContinueWatchingRoute
  AppForYouRoute: typeof AppForYouRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLatestEpisodesRoute: typeof AppLatestEpisodesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSimulcastRoute: typeof AppSimulcastRoute
  AppTrendingRoute: typeof AppTrendingRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppAnimeIdRoute: typeof AppAnimeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppContinueWatchingRoute: AppContinueWatchingRoute,
  AppForYouRoute: AppForYouRoute,
  AppHomeRoute: AppHomeRoute,
  AppLatestEpisodesRoute: AppLatestEpisodesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSimulcastRoute: AppSimulcastRoute,
  AppTrendingRoute: AppTrendingRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppAnimeIdRoute: AppAnimeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
